// module2-web-components/random-list-v4/RandomListComponent.js
//This will be a parameter
const myList = ["apple", "pineapple", "pen"];

export default class RandomList extends HTMLElement {

    constructor() {
        super();
        this.staticList = [...myList];
        this.listA = [...myList];
        this.listB = [];

        let templateContent = this._getTemplateContent();
        //No need to store variable shadowRoot, it is already part of the HTMLElement spec now.
        let shadowRoot = this.attachShadow({ mode: "open" });
        shadowRoot.appendChild(templateContent.cloneNode(true));
    }

    connectedCallback() {
        console.log("Connected component");
        this._populateStaticList();
        this._setEventListeners();
    }

    _getTemplateContent() {
        const template = document.createElement("template");
        template.innerHTML = `
            <h2>Original list of elements</h2>
            <ul id="originalList"></ul>

            <button id="pullButton">Pull Element</button>
            <button id="resetButton">Reset</button>

            <h2>Random elements removed from list</h2>
            <ol id="pulledList"></ul>
        `;
        return template.content;
    }

    _populateStaticList() {
        let shadowRoot = this.shadowRoot;
        const ul = shadowRoot.getElementById("originalList");
        this.staticList.forEach(elem => {
            ul.insertAdjacentHTML('beforeend', `<li>${elem}</li>`);
        });
    }

    _setEventListeners() {
        let shadowRoot = this.shadowRoot;
        let pullButton = shadowRoot.getElementById("pullButton");
        let resetButton = shadowRoot.getElementById("resetButton");

        pullButton.addEventListener("click", (e) => {
            console.log('listend to click event');
            console.log(e);
            this._pullElement();
        });

        resetButton.addEventListener("click", (e) => {
            console.log('listend to reset click event');
            console.log(e);
            this._resetList();
        });

    }

    _pullElement() {
        const randomElem = this._pullRandomElementFromList();
        if (!randomElem)
            return;
        this._addElementToPulledList(randomElem);
    }

    _pullRandomElementFromList() {
        if (!this.listA.length)
            return null;
        const randomIndex = Math.floor(Math.random() * this.listA.length);
        const randomElem = this.listA.splice(randomIndex, 1)[0];
        this.listB.push(randomElem);
        return randomElem;
    }

    _addElementToPulledList(elem) {
        let shadowRoot = this.shadowRoot;
        const ul = shadowRoot.getElementById("pulledList");
        ul.insertAdjacentHTML('beforeend', `<li>${elem}</li>`);
    }

    _resetList() {
        this.listA = [...this.staticList];
        this.listB = [];
        let shadowRoot = this.shadowRoot;
        const ul = shadowRoot.getElementById("pulledList");
        ul.innerHTML = "";
    }
}

customElements.define("random-list", RandomList);

// module3-react-intro/props-vs-classess/lecture8-classes/src/components/RandomList.jsx
import React, { Component } from 'react';
import './RandomList.css'

class RandomList extends Component {

    constructor(props) {
        super(props);
        
        this.listA = [...this.props.list];
        this.state = {
            randomList: []
        }

        this.handlePull = this.handlePull.bind(this);
        this.handleReset = this.handleReset.bind(this);
    }

    render() {
        return (
            <div className="randomList">
                <div>
                    <h2>Original list of elements</h2>
                    <ul className="originalList">
                        {this.props.list.map(elem => (
                            <li key={elem}>{elem}</li>
                        ))}
                    </ul>
                    <button onClick={this.handlePull}>Pull Element</button>
                    <button onClick={this.handleReset}>Reset</button>
                </div>

                <div>
                    <h2>Random elements removed from list</h2>
                    <ol className="pulledList">
                        {this.state.randomList.map(elem => (
                                <li key={elem}>{elem}</li>
                            )
                        )}
                    </ol>
                </div>
            </div>
        );
    }

    handlePull() {
        if (!this.listA.length)
            return null;
        const randomIndex = Math.floor(Math.random() * this.listA.length);
        const randomElem = this.listA.splice(randomIndex, 1)[0];
        //Remember, the state is changeable but immutable! We cannot "push" elements to the list
        //we have to create a new list with the new element.
        this.setState((state)=>{
            const randomList = [...state.randomList, randomElem];
            return {
                randomList
            }
        });
    }

    handleReset() {
        this.setState({randomList: []}, ()=>{
            this.listA = [...this.props.list];
        });
    }

    static defaultProps = {
        list: ['apple', 'pinnaple', 'pen']
    };
}

export default RandomList;
